sonar.projectKey=gh0stf1ghter_Assesment-task_Frontend
sonar.organization=gh0stf1ghter

sonar.sources=src
sonar.sourceEncoding=UTF-8

sonar.exclusions=**/node_modules/**,**/dist/**,**/*.css

sonar.coverage.exclusions=src/pages/**,src/components/**,src/context/**,src/main.tsx,src/router.tsx

sonar.tests=tests
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx
sonar.javascript.lcov.reportPaths=coverage/lcov.info
