# Local development overrides
services:
  data-ingestor:
    environment:
      # Use shorter poll interval for local testing
    volumes:
      - ./DataIngestor:/app/src:ro

  dataprocessor:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8090
      - ASPNETCORE_HTTPS_PORTS=8091
    ports:
      - "8090"
      - "8091"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
