// ============================================================================
// grpc_client.rs — gRPC client wrapper for the DataProcessor services
// ============================================================================
//
// This module wraps the four gRPC service clients generated from
// `proto/parameters.proto` and exposes them through a single `GrpcClient`
// struct that the rest of the application (the GraphQL resolvers) can use.
//
// Purpose and intent (for a .NET developer)
// ─────────────────────────────────────────
// If you come from .NET (Grpc.Net.Client / Grpc.Tools), think of this file as
// a small "service" that holds typed gRPC clients (one per proto service) and
// exposes higher-level, application-friendly methods that return DTOs.
// The GraphQL resolvers call these methods instead of directly manipulating
// the generated proto types.
//
// High-level mapping table
// ────────────────────────
// Concept                      │ C# / .NET                     │ Rust / tonic
// ─────────────────────────────┼───────────────────────────────┼─────────────────────────────
// gRPC channel                 │ GrpcChannel.ForAddress(url)   │ tonic::transport::Channel
// Typed service client         │ AirQualityService.            │ AirQualityServiceClient
//                              │   AirQualityServiceClient     │   <Channel>
// Async method                 │ async Task<T>                 │ async fn → Future<Output=T>
// Error propagation            │ throw / catch                 │ Result<T, E> + ? operator
// Nullable value               │ T? / Nullable<T>              │ Option<T>
// Timestamp (proto WKT)        │ Google.Protobuf.              │ prost_types::Timestamp
//                              │   WellKnownTypes.Timestamp    │
// Timestamp (app layer)        │ DateTime / DateTimeOffset     │ chrono::DateTime<Utc>
//
// Generated code (build.rs / tonic_build)
// ───────────────────────────────────────
// `build.rs` uses `tonic_build` (a Rust build-time helper) to compile the
// `.proto` files into Rust source and places the output into Cargo's OUT_DIR.
// The `include_proto!` macro below then pulls that generated file into this
// crate as the `proto` module. This is similar in purpose to the C# code
// generated by Grpc.Tools (but the file placement and usage are Rust-idiomatic).
//
// Practical notes for a .NET developer reading the code:
// - The generated types (e.g. `AirQualityMessage`) are plain structs produced
//   by `prost` and `tonic`. Optional proto fields become `Option<T>` in Rust,
//   analogous to nullable/reference types in C#.
// - Each `service FooService` in the proto becomes a client type named
//   `foo_service_client::FooServiceClient<Channel>`; compare this to the
//   generated `FooService.FooServiceClient` in C#.
// - This module maps those generated proto types into simple DTOs (Rust
//   structs) so the rest of the app (GraphQL layer) doesn't depend on the
//   generated code shape. In .NET you'd commonly map generated messages into
//   application models (AutoMapper / manual mapping).
//
// Error handling approach
// ───────────────────────
// - Rust uses `Result<T, E>` rather than exceptions. This file uses a boxed
//   error alias (`Box<dyn Error + Send + Sync>`) so different underlying
//   error types (network, codec, domain errors returned by the server) can
//   be returned from the same function. The GraphQL layer converts these into
//   GraphQL errors for clients (see schema.rs).
//
// ============================================================================

use chrono::{DateTime, Utc};
use tonic::transport::{Channel, ClientTlsConfig};
use tracing::instrument;

// Pull in every type generated from the proto file.
// The string "parameters" matches the `package parameters;` declaration in
// the .proto file — that is what prost uses as the file name for the output.
//
// .NET parallel: `using DataProcessor.Presentation.Protos;`
//
// Additional notes for .NET devs:
// - In C# the Grpc.Tools/Google.Protobuf toolchain generates .cs files with
//   message and client types; in Rust `prost`/`tonic_build` produce Rust
//   modules that we include with `include_proto!`.
// - The generated Rust module contains both the message structs (e.g.
//   `AirQualityMessage`) and client modules like
//   `air_quality_service_client::AirQualityServiceClient<Channel>`.
//   When reading the generated code mentally map that client type to the
//   familiar C# typed client `AirQualityService.AirQualityServiceClient`.
//
// Example mental mapping:
// - C#: var channel = GrpcChannel.ForAddress(url);
//       var client = new AirQualityService.AirQualityServiceClient(channel);
// - Rust: build an `Endpoint` from `Channel::from_shared`, call
//   `tls_config(...)` when the URI is https (tonic does not do this
//   automatically for `from_shared`), then `connect().await`.
//         let client = air_quality_service_client::AirQualityServiceClient::new(channel.clone());
//
// See the `GrpcClient` implementation below for the actual ergonomic wrapper
// that constructs these clients and exposes friendly methods returning DTOs.
pub mod proto {
    tonic::include_proto!("parameters");
}

// Bring the four generated service client types into scope.
// Each name follows the proto `service` block name, converted to snake_case
// for the module and PascalCase for the struct:
//
//   service AirQualityService  →  air_quality_service_client::AirQualityServiceClient
//   service EnergyService      →  energy_service_client::EnergyServiceClient
//   service MotionService      →  motion_service_client::MotionServiceClient
//   service RoomService        →  room_service_client::RoomServiceClient
//
// .NET parallel: the typed client classes Grpc.Tools generates, e.g.
//   AirQualityService.AirQualityServiceClient
use proto::air_quality_service_client::AirQualityServiceClient;
use proto::energy_service_client::EnergyServiceClient;
use proto::motion_service_client::MotionServiceClient;
use proto::room_service_client::RoomServiceClient;

// ============================================================================
// DTOs (Data Transfer Objects)
// ============================================================================
//
// These plain structs decouple the rest of the application from the
// auto-generated protobuf types.  Resolvers in schema.rs work with DTOs, not
// raw proto messages.
//
// .NET parallel: domain/application-layer model classes that you map generated
// gRPC messages into (often with AutoMapper or Mapster).

/// A single air-quality sensor reading from a room.
#[derive(Debug, Clone)]
pub struct AirQualityDto {
    pub id: String,
    pub room_id: String,
    pub timestamp: DateTime<Utc>,
    pub pm25: i32,     // Fine-particulate-matter concentration
    pub co2: i32,      // CO₂ level (ppm)
    pub humidity: i32, // Relative humidity (%)
}

/// A single energy-consumption reading from a room.
#[derive(Debug, Clone)]
pub struct EnergyDto {
    pub id: String,
    pub room_id: String,
    pub timestamp: DateTime<Utc>,
    pub amount: f64, // Energy amount (kWh or similar); proto `double` → Rust f64
}

/// A single motion-detection event from a room.
#[derive(Debug, Clone)]
pub struct MotionDto {
    pub id: String,
    pub room_id: String,
    pub timestamp: DateTime<Utc>,
    pub is_detected: bool,
}

/// Room metadata.
#[derive(Debug, Clone)]
pub struct RoomDto {
    pub id: String,
    pub name: String,
}

// ============================================================================
// Timestamp conversion helpers
// ============================================================================

/// Converts a `prost_types::Timestamp` (proto well-known type) to `chrono::DateTime<Utc>`.
///
/// `prost_types::Timestamp` stores seconds + nanos since the Unix epoch, the
/// same representation as `Google.Protobuf.WellKnownTypes.Timestamp` in C#.
/// The C# equivalent of this helper is `timestamp.ToDateTime()`.
fn proto_ts_to_chrono(ts: &prost_types::Timestamp) -> DateTime<Utc> {
    DateTime::from_timestamp(ts.seconds, ts.nanos as u32).unwrap_or_default()
}

/// Converts a `chrono::DateTime<Utc>` to a `prost_types::Timestamp`.
///
/// C# equivalent: `Timestamp.FromDateTime(dateTime)`.
fn chrono_to_proto_ts(dt: &DateTime<Utc>) -> prost_types::Timestamp {
    prost_types::Timestamp {
        seconds: dt.timestamp(),
        nanos: dt.timestamp_subsec_nanos() as i32,
    }
}

// ============================================================================
// Proto message → DTO converters
// ============================================================================
//
// Each function maps a generated protobuf message struct to our DTO.
// .NET parallel: mapping methods you'd write by hand or generate with Mapster /
// AutoMapper (e.g. `source.Adapt<AirQualityDto>()`).

fn air_quality_msg_to_dto(msg: proto::AirQualityMessage) -> AirQualityDto {
    AirQualityDto {
        id: msg.id,
        room_id: msg.room_id,
        // `timestamp` is `Option<prost_types::Timestamp>` in generated code.
        // `.as_ref().map(...)` converts Option<T> → Option<U>; we fall back to
        // the default (Unix epoch) if the server somehow omits the field.
        timestamp: msg.timestamp.as_ref().map(proto_ts_to_chrono).unwrap_or_default(),
        pm25: msg.pm25,
        co2: msg.co2,
        humidity: msg.humidity,
    }
}

fn energy_msg_to_dto(msg: proto::EnergyMessage) -> EnergyDto {
    EnergyDto {
        id: msg.id,
        room_id: msg.room_id,
        timestamp: msg.timestamp.as_ref().map(proto_ts_to_chrono).unwrap_or_default(),
        amount: msg.amount,
    }
}

fn motion_msg_to_dto(msg: proto::MotionMessage) -> MotionDto {
    MotionDto {
        id: msg.id,
        room_id: msg.room_id,
        timestamp: msg.timestamp.as_ref().map(proto_ts_to_chrono).unwrap_or_default(),
        is_detected: msg.is_detected,
    }
}

fn room_msg_to_dto(msg: proto::RoomMessage) -> RoomDto {
    RoomDto {
        id: msg.id,
        name: msg.name,
    }
}

// ============================================================================
// GrpcClient
// ============================================================================
//
// This section contains an ergonomic wrapper (`GrpcClient`) that holds a
// typed client for each gRPC service. It creates each typed client from a
// shared `Channel` (HTTP/2 connection) which is cheap to clone — similar to
// sharing a single `GrpcChannel` across multiple typed clients in .NET.
//
// Why we wrap the generated clients:
// - The generated clients work with proto message types. The wrapper exposes
//   higher-level methods that return application DTOs (`AirQualityDto`, …).
// - Centralising the clients makes it easy to configure the connection once
//   and mock or replace the wrapper in tests (like injecting a façade in .NET).
//
// NOTE FOR .NET DEVELOPERS: Error handling in Rust differs from exceptions.
// Instead of throwing, methods return `Result<T, E>`. The GraphQL layer
// converts `Err` into GraphQL errors. The `ClientError` alias below is a
// convenient box type that allows each method to return different concrete
// error types (tonic transport errors, prost conversion errors, etc.) while
// keeping the signature uniform. When porting ideas back to C#, you might
// choose to wrap gRPC errors into domain exceptions or a `Result<T>` type.
//
// Example correspondence:
// - Rust:    async fn get_air_qualities(...) -> Result<Vec<AirQualityDto>, ClientError>
// - C#:      public async Task<List<AirQualityDto>> GetAirQualitiesAsync(...)
//            // exceptions propagate and can be handled by calling code
//
// The boxed trait object `Box<dyn std::error::Error + Send + Sync>` is the
// closest ergonomic analogue to "any exception" in C# for return-style error
// propagation in `Result`.
///
/// Shorthand for the boxed, Send+Sync error type used by all client methods.
type ClientError = Box<dyn std::error::Error + Send + Sync>;

/// Holds gRPC client handles for all four DataProcessor services.
///
/// A single `Channel` (HTTP/2 connection) is shared across all four clients,
/// which is both efficient and idiomatic in tonic.  Cloning a `Channel` is
/// cheap — it just increments a reference count.
///
/// .NET parallel: imagine a class that DI-injects four typed gRPC clients all
/// backed by the same `GrpcChannel`:
///
///   public class GrpcClient(
///       AirQualityService.AirQualityServiceClient airQuality,
///       EnergyService.EnergyServiceClient energy,
///       MotionService.MotionServiceClient motion,
///       RoomService.RoomServiceClient room)
///   { … }
///
/// The `#[derive(Clone)]` is required so that `GrpcClient` can be stored
/// inside the `async_graphql::Schema` (which requires its data to be Clone).
/// Cloning a tonic service client is cheap (it clones the inner Channel arc).
#[derive(Debug, Clone)]
pub struct GrpcClient {
    air_quality: AirQualityServiceClient<Channel>,
    energy: EnergyServiceClient<Channel>,
    motion: MotionServiceClient<Channel>,
    room: RoomServiceClient<Channel>,
}

impl GrpcClient {
    /// Connect to the DataProcessor gRPC server at `endpoint` and return a
    /// ready-to-use `GrpcClient`.
    ///
    /// A single `Channel` is created for the endpoint and shared across all
    /// four service clients.  The connection is established eagerly (we await
    /// the actual TCP + TLS handshake), so any network error surfaces here
    /// rather than on the first RPC call.
    ///
    /// C# equivalent:
    ///   var channel = GrpcChannel.ForAddress(endpoint);
    ///   // then construct typed clients from the same channel
    #[instrument(skip(), fields(endpoint = %endpoint))]
    pub async fn connect(endpoint: String) -> Result<Self, Box<dyn std::error::Error>> {
        tracing::info!("resolving endpoint and opening HTTP/2 channel (TLS if https)");
        // `Channel::from_shared` returns a tonic `Endpoint`. For `https://` URIs you must
        // call `tls_config` yourself — unlike `Endpoint::try_from`, `from_shared` leaves
        // `tls` unset, which produces `HttpsUriWithoutTlsSupport` at connect time.
        let mut ep = Channel::from_shared(endpoint)
            .map_err(|e| -> Box<dyn std::error::Error> { Box::new(e) })?;

        if ep.uri().scheme_str() == Some("https") {
            tracing::debug!("applying ClientTlsConfig with enabled root CAs for HTTPS");
            ep = ep
                .tls_config(ClientTlsConfig::new().with_enabled_roots())
                .map_err(|e| -> Box<dyn std::error::Error> { Box::new(e) })?;
        }

        // Eagerly establish the connection. `.connect_lazy()` would connect on first RPC.
        let channel = ep
            .connect()
            .await
            .map_err(|e| -> Box<dyn std::error::Error> { Box::new(e) })?;

        tracing::info!("connected; wiring AirQuality, Energy, Motion, and Room clients");

        Ok(Self {
            // Each service client wraps a clone of the same channel.
            // `Channel::clone` is O(1) — it only copies an Arc pointer.
            air_quality: AirQualityServiceClient::new(channel.clone()),
            energy: EnergyServiceClient::new(channel.clone()),
            motion: MotionServiceClient::new(channel.clone()),
            room: RoomServiceClient::new(channel),
        })
    }

    // =========================================================================
    // Air Quality RPCs
    // =========================================================================

    /// Calls `AirQualityService.GetAirQualities` and returns a list of DTOs.
    ///
    /// All filter parameters are optional.  When omitted the server returns
    /// every record it holds.
    ///
    /// C# equivalent (approx):
    ///   public async Task<List<AirQualityDto>> GetAirQualitiesAsync(
    ///       DateTime? timestampStart, DateTime? timestampEnd, string? roomId)
    #[instrument(skip(self), level = "debug", err)]
    pub async fn get_air_qualities(
        &self,
        timestamp_start: Option<DateTime<Utc>>,
        timestamp_end: Option<DateTime<Utc>>,
        room_id: Option<String>,
    ) -> Result<Vec<AirQualityDto>, ClientError> {
        let request = proto::GetAirQualitiesRequest {
            // `Option<DateTime<Utc>>` → `Option<prost_types::Timestamp>`:
            // `.as_ref()` borrows the inner value so we don't move out of the
            // Option; `.map(f)` applies the conversion if the value is Some.
            timestamp_start: timestamp_start.as_ref().map(chrono_to_proto_ts),
            timestamp_end: timestamp_end.as_ref().map(chrono_to_proto_ts),
            room_id,
        };

        // `tonic::Request::new(...)` wraps the message with metadata headers
        // (analogous to setting gRPC call headers in C#).
        // `.clone()` on the client is cheap — see the Channel note above.
        let response = self
            .air_quality
            .clone()
            .get_air_qualities(tonic::Request::new(request))
            .await?
            .into_inner(); // unwrap the tonic::Response wrapper

        // Every response uses a `oneof result { data | error }` pattern.
        // prost generates an Option<enum> field named `result`.  We match on
        // the variants to handle success and error branches separately.
        //
        // .NET parallel: checking a discriminated union / OneOf result pattern.
        match response.result {
            Some(proto::get_air_qualities_response::Result::Data(list)) => {
                // Convert each proto message into our DTO using the mapper above.
                // `.into_iter().map(f).collect()` is LINQ's `.Select(f).ToList()`.
                Ok(list.air_qualities.into_iter().map(air_quality_msg_to_dto).collect())
            }
            Some(proto::get_air_qualities_response::Result::Error(err)) => {
                // The server returned a domain error; surface it as a Rust error.
                Err(format!("gRPC error (code {}): {}", err.code, err.message).into())
            }
            // `None` means the server sent a response with no `result` field set —
            // treat it as an empty result set rather than a hard error.
            None => Ok(vec![]),
        }
    }

    /// Calls `AirQualityService.GetAirQuality` and returns a single DTO.
    ///
    /// C# equivalent:
    ///   public async Task<AirQualityDto> GetAirQualityAsync(string id)
    #[instrument(skip(self), level = "debug", err)]
    pub async fn get_air_quality(&self, air_quality_id: String) -> Result<AirQualityDto, ClientError> {
        let request = proto::GetAirQualityRequest { air_quality_id };

        let response = self
            .air_quality
            .clone()
            .get_air_quality(tonic::Request::new(request))
            .await?
            .into_inner();

        match response.result {
            Some(proto::get_air_quality_response::Result::Data(msg)) => {
                Ok(air_quality_msg_to_dto(msg))
            }
            Some(proto::get_air_quality_response::Result::Error(err)) => {
                Err(format!("gRPC error (code {}): {}", err.code, err.message).into())
            }
            None => Err("GetAirQuality returned no data".into()),
        }
    }

    // =========================================================================
    // Energy RPCs
    // =========================================================================

    /// Calls `EnergyService.GetEnergies` and returns a list of DTOs.
    ///
    /// C# equivalent:
    ///   public async Task<List<EnergyDto>> GetEnergiesAsync(
    ///       DateTime? timestampStart, DateTime? timestampEnd, string? roomId)
    #[instrument(skip(self), level = "debug", err)]
    pub async fn get_energies(
        &self,
        timestamp_start: Option<DateTime<Utc>>,
        timestamp_end: Option<DateTime<Utc>>,
        room_id: Option<String>,
    ) -> Result<Vec<EnergyDto>, ClientError> {
        let request = proto::GetEnergiesRequest {
            timestamp_start: timestamp_start.as_ref().map(chrono_to_proto_ts),
            timestamp_end: timestamp_end.as_ref().map(chrono_to_proto_ts),
            room_id,
        };

        let response = self
            .energy
            .clone()
            .get_energies(tonic::Request::new(request))
            .await?
            .into_inner();

        match response.result {
            Some(proto::get_energies_response::Result::Data(list)) => {
                Ok(list.energies.into_iter().map(energy_msg_to_dto).collect())
            }
            Some(proto::get_energies_response::Result::Error(err)) => {
                Err(format!("gRPC error (code {}): {}", err.code, err.message).into())
            }
            None => Ok(vec![]),
        }
    }

    /// Calls `EnergyService.GetEnergy` and returns a single DTO.
    ///
    /// C# equivalent:
    ///   public async Task<EnergyDto> GetEnergyAsync(string id)
    #[instrument(skip(self), level = "debug", err)]
    pub async fn get_energy(&self, energy_id: String) -> Result<EnergyDto, ClientError> {
        let request = proto::GetEnergyRequest { energy_id };

        let response = self
            .energy
            .clone()
            .get_energy(tonic::Request::new(request))
            .await?
            .into_inner();

        match response.result {
            Some(proto::get_energy_response::Result::Data(msg)) => Ok(energy_msg_to_dto(msg)),
            Some(proto::get_energy_response::Result::Error(err)) => {
                Err(format!("gRPC error (code {}): {}", err.code, err.message).into())
            }
            None => Err("GetEnergy returned no data".into()),
        }
    }

    // =========================================================================
    // Motion RPCs
    // =========================================================================

    /// Calls `MotionService.GetMotions` and returns a list of DTOs.
    ///
    /// C# equivalent:
    ///   public async Task<List<MotionDto>> GetMotionsAsync(
    ///       DateTime? timestampStart, DateTime? timestampEnd, string? roomId)
    #[instrument(skip(self), level = "debug", err)]
    pub async fn get_motions(
        &self,
        timestamp_start: Option<DateTime<Utc>>,
        timestamp_end: Option<DateTime<Utc>>,
        room_id: Option<String>,
    ) -> Result<Vec<MotionDto>, ClientError> {
        let request = proto::GetMotionsRequest {
            timestamp_start: timestamp_start.as_ref().map(chrono_to_proto_ts),
            timestamp_end: timestamp_end.as_ref().map(chrono_to_proto_ts),
            room_id,
        };

        let response = self
            .motion
            .clone()
            .get_motions(tonic::Request::new(request))
            .await?
            .into_inner();

        match response.result {
            Some(proto::get_motions_response::Result::Data(list)) => {
                Ok(list.motions.into_iter().map(motion_msg_to_dto).collect())
            }
            Some(proto::get_motions_response::Result::Error(err)) => {
                Err(format!("gRPC error (code {}): {}", err.code, err.message).into())
            }
            None => Ok(vec![]),
        }
    }

    /// Calls `MotionService.GetMotion` and returns a single DTO.
    ///
    /// C# equivalent:
    ///   public async Task<MotionDto> GetMotionAsync(string id)
    #[instrument(skip(self), level = "debug", err)]
    pub async fn get_motion(&self, motion_id: String) -> Result<MotionDto, ClientError> {
        let request = proto::GetMotionRequest { motion_id };

        let response = self
            .motion
            .clone()
            .get_motion(tonic::Request::new(request))
            .await?
            .into_inner();

        match response.result {
            Some(proto::get_motion_response::Result::Data(msg)) => Ok(motion_msg_to_dto(msg)),
            Some(proto::get_motion_response::Result::Error(err)) => {
                Err(format!("gRPC error (code {}): {}", err.code, err.message).into())
            }
            None => Err("GetMotion returned no data".into()),
        }
    }

    // =========================================================================
    // Room RPCs
    // =========================================================================

    /// Calls `RoomService.GetRooms` and returns a list of DTOs.
    ///
    /// Note: the `GetRoomsRequest` in the proto does NOT accept a `room_id`
    /// filter — it returns rooms that had activity in the given time window.
    /// Use `get_room` for fetching a specific room by ID.
    ///
    /// C# equivalent:
    ///   public async Task<List<RoomDto>> GetRoomsAsync(
    ///       DateTime? timestampStart, DateTime? timestampEnd)
    #[instrument(skip(self), level = "debug", err)]
    pub async fn get_rooms(
        &self,
        timestamp_start: Option<DateTime<Utc>>,
        timestamp_end: Option<DateTime<Utc>>,
    ) -> Result<Vec<RoomDto>, ClientError> {
        let request = proto::GetRoomsRequest {
            timestamp_start: timestamp_start.as_ref().map(chrono_to_proto_ts),
            timestamp_end: timestamp_end.as_ref().map(chrono_to_proto_ts),
        };

        let response = self
            .room
            .clone()
            .get_rooms(tonic::Request::new(request))
            .await?
            .into_inner();

        match response.result {
            Some(proto::get_rooms_response::Result::Data(list)) => {
                Ok(list.rooms.into_iter().map(room_msg_to_dto).collect())
            }
            Some(proto::get_rooms_response::Result::Error(err)) => {
                Err(format!("gRPC error (code {}): {}", err.code, err.message).into())
            }
            None => Ok(vec![]),
        }
    }

    /// Calls `RoomService.GetRoom` and returns a single DTO.
    ///
    /// C# equivalent:
    ///   public async Task<RoomDto> GetRoomAsync(string id)
    #[instrument(skip(self), level = "debug", err)]
    pub async fn get_room(&self, room_id: String) -> Result<RoomDto, ClientError> {
        let request = proto::GetRoomRequest { room_id };

        let response = self
            .room
            .clone()
            .get_room(tonic::Request::new(request))
            .await?
            .into_inner();

        match response.result {
            Some(proto::get_room_response::Result::Data(msg)) => Ok(room_msg_to_dto(msg)),
            Some(proto::get_room_response::Result::Error(err)) => {
                Err(format!("gRPC error (code {}): {}", err.code, err.message).into())
            }
            None => Err("GetRoom returned no data".into()),
        }
    }
}
