sonar.projectKey=gh0stf1ghter_Assesment-task_DataIngestor
sonar.organization=gh0stf1ghter

sonar.sources=.
sonar.exclusions=**/*_test.go
sonar.sourceEncoding=UTF-8

sonar.tests=.
sonar.test.inclusions=**/*_test.go
sonar.go.coverage.reportPaths=coverage.out

sonar.coverage.exclusions=main.go
