sonar.projectKey=DmitriyG0r4anin_Assesment-task_DataIngestor
sonar.organization=gh0stf1ghter

# Source directory (relative to this file)
sonar.sources=.

# Go coverage report produced by 'go test -coverprofile=coverage.out'
sonar.go.coverage.reportPaths=coverage.out

# Encoding of the source code
sonar.sourceEncoding=UTF-8
