name: NotificationsService - Build & Analyze

on:
  push:
    branches:
      - main
    paths:
      - "NotificationsService/**"
      - ".github/workflows/notifications-service.yml"

  pull_request:
    branches: ["**"]
    paths:
      - "NotificationsService/**"
      - ".github/workflows/notifications-service.yml"

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Sonar Scan
        uses: highbyte/sonarscan-dotnet@252f699a9c4e005bf3902d44a1c6c0aea43c678e
        with:
          sonarProjectKey: gh0stf1ghter_Assesment-task_NotificationsService
          sonarProjectName: gh0stf1ghter_Assesment-task_NotificationsService
          sonarOrganization: gh0stf1ghter
          dotnetBuildArguments: ./NotificationsService --configuration Release
          dotnetTestArguments: ./NotificationsService --no-build --configuration Release --verbosity normal --logger trx --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover
          sonarBeginArguments: /d:sonar.projectBaseDir="/github/workspace/NotificationsService" /d:sonar.cs.opencover.reportsPaths="NotificationsService/**/TestResults/**/coverage.opencover.xml" -d:sonar.cs.vstest.reportsPaths="NotificationsService/**/TestResults/*.trx" /d:sonar.coverage.exclusions="${{env.EXCLUDE_FROM_COVERAGE}}" /d:sonar.exclusions="${{env.EXCLUDE_FROM_SONAR}}"
    env:
      EXCLUDE_FROM_COVERAGE: "**/Program.cs, **/Models/*, **/Configuration/*, **/Serialization/*, **/Services/*, **/Hubs/*"
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      EXCLUDE_FROM_SONAR: "**/Dockerfile"
